# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import app.shared.proto.ml_pb2 as ml__pb2

GRPC_GENERATED_VERSION = '1.81.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in ml_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class MLServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.PredictTransactionCategory = channel.unary_unary(
                '/ml.MLService/PredictTransactionCategory',
                request_serializer=ml__pb2.PredictCategoryRequest.SerializeToString,
                response_deserializer=ml__pb2.PredictCategoryResponse.FromString,
                _registered_method=True)
        self.ClassifyTransactionMultilingual = channel.unary_unary(
                '/ml.MLService/ClassifyTransactionMultilingual',
                request_serializer=ml__pb2.ClassifyRequest.SerializeToString,
                response_deserializer=ml__pb2.ClassifyResponse.FromString,
                _registered_method=True)
        self.DetectChatStress = channel.unary_unary(
                '/ml.MLService/DetectChatStress',
                request_serializer=ml__pb2.StressRequest.SerializeToString,
                response_deserializer=ml__pb2.StressResponse.FromString,
                _registered_method=True)
        self.ForecastCashflow = channel.unary_unary(
                '/ml.MLService/ForecastCashflow',
                request_serializer=ml__pb2.ForecastRequest.SerializeToString,
                response_deserializer=ml__pb2.ForecastResponse.FromString,
                _registered_method=True)
        self.DetectBehaviorAnomaly = channel.unary_unary(
                '/ml.MLService/DetectBehaviorAnomaly',
                request_serializer=ml__pb2.BehaviorAnomalyRequest.SerializeToString,
                response_deserializer=ml__pb2.BehaviorAnomalyResponse.FromString,
                _registered_method=True)
        self.CalculateRiskScore = channel.unary_unary(
                '/ml.MLService/CalculateRiskScore',
                request_serializer=ml__pb2.RiskScoreRequest.SerializeToString,
                response_deserializer=ml__pb2.RiskScoreResponse.FromString,
                _registered_method=True)
        self.DetectSequenceAnomaly = channel.unary_unary(
                '/ml.MLService/DetectSequenceAnomaly',
                request_serializer=ml__pb2.SequenceAnomalyRequest.SerializeToString,
                response_deserializer=ml__pb2.SequenceAnomalyResponse.FromString,
                _registered_method=True)
        self.DetectInsiderThreat = channel.unary_unary(
                '/ml.MLService/DetectInsiderThreat',
                request_serializer=ml__pb2.InsiderThreatRequest.SerializeToString,
                response_deserializer=ml__pb2.InsiderThreatResponse.FromString,
                _registered_method=True)


class MLServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def PredictTransactionCategory(self, request, context):
        """M1: RF + TF-IDF transaction category classifier
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ClassifyTransactionMultilingual(self, request, context):
        """M2: BERT multilingual transaction text classifier
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DetectChatStress(self, request, context):
        """M3: BERT-based chat stress / coercion detector
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ForecastCashflow(self, request, context):
        """RF cashflow forecasting (arima_<account>.pkl = RandomForestRegressor)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DetectBehaviorAnomaly(self, request, context):
        """Isolation Forest (global + per-user SVM) behavioral anomaly detector
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CalculateRiskScore(self, request, context):
        """M4: dual-head RiskMLP coercion risk scorer
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DetectSequenceAnomaly(self, request, context):
        """LSTM autoencoder transaction sequence anomaly detector
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DetectInsiderThreat(self, request, context):
        """GraphSAGE insider threat detector (employee-account collusion graph)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MLServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'PredictTransactionCategory': grpc.unary_unary_rpc_method_handler(
                    servicer.PredictTransactionCategory,
                    request_deserializer=ml__pb2.PredictCategoryRequest.FromString,
                    response_serializer=ml__pb2.PredictCategoryResponse.SerializeToString,
            ),
            'ClassifyTransactionMultilingual': grpc.unary_unary_rpc_method_handler(
                    servicer.ClassifyTransactionMultilingual,
                    request_deserializer=ml__pb2.ClassifyRequest.FromString,
                    response_serializer=ml__pb2.ClassifyResponse.SerializeToString,
            ),
            'DetectChatStress': grpc.unary_unary_rpc_method_handler(
                    servicer.DetectChatStress,
                    request_deserializer=ml__pb2.StressRequest.FromString,
                    response_serializer=ml__pb2.StressResponse.SerializeToString,
            ),
            'ForecastCashflow': grpc.unary_unary_rpc_method_handler(
                    servicer.ForecastCashflow,
                    request_deserializer=ml__pb2.ForecastRequest.FromString,
                    response_serializer=ml__pb2.ForecastResponse.SerializeToString,
            ),
            'DetectBehaviorAnomaly': grpc.unary_unary_rpc_method_handler(
                    servicer.DetectBehaviorAnomaly,
                    request_deserializer=ml__pb2.BehaviorAnomalyRequest.FromString,
                    response_serializer=ml__pb2.BehaviorAnomalyResponse.SerializeToString,
            ),
            'CalculateRiskScore': grpc.unary_unary_rpc_method_handler(
                    servicer.CalculateRiskScore,
                    request_deserializer=ml__pb2.RiskScoreRequest.FromString,
                    response_serializer=ml__pb2.RiskScoreResponse.SerializeToString,
            ),
            'DetectSequenceAnomaly': grpc.unary_unary_rpc_method_handler(
                    servicer.DetectSequenceAnomaly,
                    request_deserializer=ml__pb2.SequenceAnomalyRequest.FromString,
                    response_serializer=ml__pb2.SequenceAnomalyResponse.SerializeToString,
            ),
            'DetectInsiderThreat': grpc.unary_unary_rpc_method_handler(
                    servicer.DetectInsiderThreat,
                    request_deserializer=ml__pb2.InsiderThreatRequest.FromString,
                    response_serializer=ml__pb2.InsiderThreatResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ml.MLService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ml.MLService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MLService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def PredictTransactionCategory(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ml.MLService/PredictTransactionCategory',
            ml__pb2.PredictCategoryRequest.SerializeToString,
            ml__pb2.PredictCategoryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ClassifyTransactionMultilingual(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ml.MLService/ClassifyTransactionMultilingual',
            ml__pb2.ClassifyRequest.SerializeToString,
            ml__pb2.ClassifyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DetectChatStress(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ml.MLService/DetectChatStress',
            ml__pb2.StressRequest.SerializeToString,
            ml__pb2.StressResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ForecastCashflow(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ml.MLService/ForecastCashflow',
            ml__pb2.ForecastRequest.SerializeToString,
            ml__pb2.ForecastResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DetectBehaviorAnomaly(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ml.MLService/DetectBehaviorAnomaly',
            ml__pb2.BehaviorAnomalyRequest.SerializeToString,
            ml__pb2.BehaviorAnomalyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CalculateRiskScore(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ml.MLService/CalculateRiskScore',
            ml__pb2.RiskScoreRequest.SerializeToString,
            ml__pb2.RiskScoreResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DetectSequenceAnomaly(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ml.MLService/DetectSequenceAnomaly',
            ml__pb2.SequenceAnomalyRequest.SerializeToString,
            ml__pb2.SequenceAnomalyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DetectInsiderThreat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ml.MLService/DetectInsiderThreat',
            ml__pb2.InsiderThreatRequest.SerializeToString,
            ml__pb2.InsiderThreatResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
