services:
  kafdrop:
    image: obsidiandynamics/kafdrop
    restart: unless-stopped
    ports:
      - "9000:9000"
    environment:
      KAFKA_BROKERCONNECT: "kafka:29092"
    depends_on:
      - kafka

  kafka:
    image: obsidiandynamics/kafka
    restart: unless-stopped
    ports:
      - "2181:2181"
      - "9092:9092"
      - "29092:29092"
    environment:
      KAFKA_LISTENERS: "INTERNAL://:29092,EXTERNAL://:9092"
      KAFKA_ADVERTISED_LISTENERS: "INTERNAL://kafka:29092,EXTERNAL://localhost:9092"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT"
      KAFKA_INTER_BROKER_LISTENER_NAME: "INTERNAL"
      KAFKA_ZOOKEEPER_SESSION_TIMEOUT: "6000"
      KAFKA_RESTART_ATTEMPTS: "10"
      KAFKA_RESTART_DELAY: "5"
      ZOOKEEPER_AUTOPURGE_PURGE_INTERVAL: "0"

  redis:
    image: redis/redis-stack:latest
    restart: unless-stopped
    ports:
      - "6379:6379"
      - "8001:8001"

  backend_app:
    build: 
      context: ./backend
      dockerfile: Dockerfile.app
    container_name: wealthvault_backend_app
    restart: unless-stopped
    ports:
      - "8000:8000"
    env_file: ./backend/.env
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/docs"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - model_data:/app/app/ml_model/saved   # ✅ named volume
    depends_on:
      - redis
      - kafka
  backend_compliance_app:
    build: 
      context: ./backend
      dockerfile: Dockerfile.compliance_app
    container_name: wealthvault_backend_compliance_app
    restart: unless-stopped
    ports:
      - "8002:8002"
    env_file: ./backend/.env
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/docs"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - model_data:/app/app/ml_model/saved   # ✅ same shared volume
    depends_on:
      - redis
      - kafka

  frontend:
    build: ./frontend
    container_name: wealthvault-frontend
    restart: unless-stopped
    ports:
      - "5173:5173"
    env_file: ./frontend/.env
    depends_on:
      backend_app:
        condition: service_healthy
      backend_compliance_app:
        condition: service_healthy

# ✅ volumes defined at bottom
volumes:
  model_data: