import React, { useEffect, useState } from 'react';
import { transactionsAPI } from '../api';
import { Download } from 'lucide-react';
import { useAuthStore } from '../store';
import { useTranslation } from '../hooks/useTranslation';
import PageInfoButton from '../components/PageInfoButton';
import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import toast from 'react-hot-toast';
import PageLoader from '../components/animation/PageLoader';

const Transactions: React.FC = () => {
  const { t } = useTranslation();
  const [transactions, setTransactions] = useState<any[]>([]);
  const [loading, setLoading] = useState(true);
  const [filter, setFilter] = useState('');
  const [timeRange, setTimeRange] = useState('');
  const { user } = useAuthStore();
  const [downloading, setDownloading] = useState(false);
  const [showInfo, setShowInfo] = useState(false);

  const handleDownloadStatement = async () => {
    if (transactions.length === 0) {
      toast.error('No transactions to download');
      return;
    }
    setDownloading(true);

    try {
      const doc = new jsPDF();

      // Branding Header
      doc.setFontSize(22);
      doc.setTextColor(15, 118, 110);
      doc.text('WealthVault', 14, 20);

      doc.setFontSize(10);
      doc.setTextColor(100, 100, 100);
      doc.text('Official Account Statement', 14, 26);

      doc.setFontSize(12);
      doc.setTextColor(0, 0, 0);
      doc.text(`Account Holder: ${user?.full_name || 'Customer'}`, 14, 40);
      doc.text(`Email: ${user?.email || 'N/A'}`, 14, 46);
      doc.text(`Statement Date: ${new Date().toLocaleDateString('en-IN')}`, 14, 52);

      const totalCredit = transactions
        .filter(t => t.transaction_type === 'credit')
        .reduce((sum, t) => sum + t.amount, 0);
      const totalDebit = transactions
        .filter(t => t.transaction_type === 'debit')
        .reduce((sum, t) => sum + t.amount, 0);

      doc.text(`Total Credit: +Rs ${totalCredit.toLocaleString('en-IN')}`, 130, 40);
      doc.text(`Total Debit: -Rs ${totalDebit.toLocaleString('en-IN')}`, 130, 46);

      doc.text(`Filter: ${filter ? (filter.charAt(0).toUpperCase() + filter.slice(1)) : 'All Categories'}`, 14, 62);

      const tableColumn = ["Date", "Description", "Category", "Type", "Amount (INR)", "Status"];
      const tableRows: any[] = [];

      transactions.forEach(txn => {
        const date = new Date(txn.created_at).toLocaleDateString('en-IN', { day: '2-digit', month: 'short', year: 'numeric' });
        const desc = txn.description || '--';
        const cat = txn.category.charAt(0).toUpperCase() + txn.category.slice(1);
        const type = txn.transaction_type.toUpperCase();
        const amt = `${txn.transaction_type === 'credit' ? '+' : '-'} ${txn.amount.toLocaleString('en-IN')}`;
        const status = txn.status.toUpperCase();
        tableRows.push([date, desc, cat, type, amt, status]);
      });

      autoTable(doc, {
        head: [tableColumn],
        body: tableRows,
        startY: 68,
        theme: 'striped',
        headStyles: { fillColor: [15, 118, 110] },
      });

      const pageCount = (doc as any).internal.getNumberOfPages();
      for (let i = 1; i <= pageCount; i++) {
        doc.setPage(i);
        doc.setFontSize(8);
        doc.setTextColor(150);
        doc.text(
          `Page ${i} of ${pageCount} | Generated by WealthVault Secure Banking`,
          doc.internal.pageSize.width / 2,
          doc.internal.pageSize.height - 10,
          { align: 'center' }
        );
      }

      doc.save(`Download_Statement_${new Date().toISOString().split('T')[0]}.pdf`);
      toast.success('Bank statement downloaded successfully');
    } catch (err) {
      console.error(err);
      toast.error('Failed to generate statement');
    } finally {
      setDownloading(false);
    }
  };

  useEffect(() => {
    loadTransactions();
  }, [filter, timeRange]);

  const loadTransactions = async () => {
    try {
      setLoading(true);
      const params: any = { limit: 100 };
      if (filter) params.category = filter;
      if (timeRange) params.days = timeRange;
      const res = await transactionsAPI.getAll(params);
      setTransactions(res.data);
    } catch (err) { console.error(err); }
    finally { setLoading(false); }
  };

  if (loading) return <PageLoader label="Loading transactions" />;

  const categories = ['salary', 'food', 'shopping', 'bills', 'entertainment', 'travel', 'healthcare', 'education', 'investment', 'transfer', 'other'];

  return (
    <div>
      <div className="page-header" style={{ alignItems: 'flex-start' }}>
        <div>
          <h2 style={{ margin: 0, paddingBottom: 4, display: 'flex', alignItems: 'center' }}>
            {t('nav.transactions')}
            <PageInfoButton
              pageTitle={t('nav.transactions')}
              items={[
                { title: 'Account Statement', description: 'A comprehensive ledger record of your payments, income, and transfers across all accounts.' },
                { title: 'Transaction Types', description: 'Credit (money in) and Debit (money out) classifications to help organize your finances.' },
                { title: 'ML Categorization', description: 'Artificial Intelligence automatically sorts your transactions into categories like Food, Transport, Utilities, etc.' }
              ]}
            />
          </h2>
          <p>View your transaction history</p>
        </div>
        <div style={{ display: 'flex', gap: '12px', alignItems: 'center' }}>
          <select
            className="form-select"
            value={timeRange}
            onChange={(e) => setTimeRange(e.target.value)}
            style={{ width: 140 }}
            id="txn-time-filter"
          >
            <option value="">All Time</option>
            <option value="1">Past Day</option>
            <option value="30">Past Month</option>
            <option value="365">Past Year</option>
          </select>
          <select
            className="form-select"
            value={filter}
            onChange={(e) => setFilter(e.target.value)}
            style={{ width: 150 }}
            id="txn-category-filter"
          >
            <option value="">All Categories</option>
            {categories.map((c) => (
              <option key={c} value={c} style={{ textTransform: 'capitalize' }}>
                {c.charAt(0).toUpperCase() + c.slice(1)}
              </option>
            ))}
          </select>
          <button
            className="btn btn-outline flex items-center gap-2"
            onClick={handleDownloadStatement}
            disabled={downloading}
            style={{ minWidth: 140 }}
            id="txn-download-btn"
          >
            {downloading ? (
              <span style={{ fontWeight: 700, fontSize: '0.8rem' }}>...</span>
            ) : (
              <Download size={18} />
            )}
            {downloading ? 'Generating...' : 'Download Statement'}
          </button>
        </div>
      </div>

      <div className="card">
        <div className="table-container">
          <table>
            <thead>
              <tr>
                <th>{t('payments.date')}</th>
                <th>{t('common.description')}</th>
                <th>{t('common.category')}</th>
                <th>{t('common.type')}</th>
                <th>{t('common.amount')}</th>
                <th>Risk</th>
                <th>{t('common.status')}</th>
              </tr>
            </thead>
            <tbody>
              {transactions.map((txn) => (
                <tr key={txn.id}>
                  <td style={{ fontSize: '0.8rem' }}>
                    {new Date(txn.created_at).toLocaleDateString('en-IN', { day: '2-digit', month: 'short', year: '2-digit' })}
                  </td>
                  <td style={{ color: 'var(--text-primary)', fontWeight: 500 }}>{txn.description || '—'}</td>
                  <td style={{ textTransform: 'capitalize' }}>{txn.category}</td>
                  <td>
                    <span style={{
                      display: 'inline-flex', alignItems: 'center', gap: 4,
                      color: txn.transaction_type === 'credit' ? 'var(--success)' : 'var(--danger)'
                    }}>
                      {txn.transaction_type === 'credit' ? '↑' : '↓'} {txn.transaction_type}
                    </span>
                  </td>
                  <td className={txn.transaction_type === 'credit' ? 'amount-credit' : 'amount-debit'} style={{ fontWeight: 600, fontFamily: 'monospace' }}>
                    {txn.transaction_type === 'credit' ? '+' : '-'}₹{txn.amount.toLocaleString('en-IN')}
                  </td>
                  <td>
                    <div style={{ display: 'flex', alignItems: 'center', gap: 6 }}>
                      <div style={{
                        width: 8, height: 8, borderRadius: '50%',
                        background: txn.risk_score > 0.7 ? 'var(--danger)' : txn.risk_score > 0.4 ? 'var(--warning)' : 'var(--success)'
                      }} />
                      <span style={{ fontSize: '0.8rem' }}>{(txn.risk_score * 100).toFixed(0)}%</span>
                    </div>
                  </td>
                  <td><span className={`badge-status ${txn.status}`}>{txn.status}</span></td>
                </tr>
              ))}
              {transactions.length === 0 && (
                <tr><td colSpan={7}><div className="empty-state"><p>No transactions found</p></div></td></tr>
              )}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  );
};

export default Transactions;
